### ISSUE TITLE
multiblockcraft criteria bug

### ISSUE THREAD

**Issue by AlmostPanda** [char3210/SlimefunAdvancements#22]
I discovered an issue with multiblockcraft criteria by using ORE_WASHER multiblock, I made a quest but it doesnt seem to work on any DUST

I think the issue is that the Ore Washer outputs not only dust but also a Stone Chunk with it

here is my quest
```
dust:
  group: basic
  name: "&a[Dust]"
  display: 
    type: COPPER_DUST
    name: "&eCreating Dust (4/4)"
    lore:
      - "&7Properly wash Sifted Ore in"
      - "&7Ore Washer, you will be rewarded"
      - "&7for your hard work"
      - ""
      - "&6Requirements:"
      - "%criteria%"
      - ""
      - "&6Reward:"
      - "&8 ➡ &760x Gravel"
      - ""    
  criteria:
    copper:
      name: "&8 ➡ &710x Copper Dust"
      type: multiblockcraft
      multiblock: ORE_WASHER
      amount: 10
      item:
        type: COPPER_DUST
    gold:
      name: " &8➡ &710x Gold Dust"
      type: multiblockcraft
      multiblock: ORE_WASHER
      amount: 10
      item:
        type: GOLD_DUST
    iron:
      name: " &8➡ &710x Iron Dust"
      type: multiblockcraft
      multiblock: ORE_WASHER
      amount: 10
      item:
        type: IRON_DUST
    aluminum:
      name: " &8➡ &710x Aluminum Dust"
      type: multiblockcraft
      multiblock: ORE_WASHER
      amount: 10
      item:
        type: ALUMINUM_DUST
    zinc:
      name: " &8➡ &710x Zinc Dust"
      type: multiblockcraft
      multiblock: ORE_WASHER
      amount: 10
      item:
        type: ZINC_DUST
    magnesium:
      name: " &8➡ &710x Magnesium Dust"
      type: multiblockcraft
      multiblock: ORE_WASHER
      amount: 10
      item:
        type: MAGNESIUM_DUST
    lead:
      name: " &8➡ &710x Lead Dust"
      type: multiblockcraft
      multiblock: ORE_WASHER
      amount: 10
      item:
        type: LEAD_DUST
    silver:
      name: " &8➡ &710x Silver Dust"
      type: multiblockcraft
      multiblock: ORE_WASHER
      amount: 10
      item:
        type: SILVER_DUST
    tin:
      name: " &8➡ &710x Tin Dust"
      type: multiblockcraft
      multiblock: ORE_WASHER
      amount: 10
      item:
        type: TIN_DUST
  reward:
    commands:
      - "cmi give %p% gravel 60 -s"
      ```
